import oracledb

# --- ORACLE CONNECTION DETAILS ---
USERNAME = "system"        # change
PASSWORD = "deva@2007"        # change
HOST = "localhost"
PORT = 1521
SERVICE = "XE"             # change if needed


def get_connection():
    dsn = oracledb.makedsn(HOST, PORT, service_name=SERVICE)
    return oracledb.connect(user=USERNAME, password=PASSWORD, dsn=dsn)


def init_db():
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("""
    BEGIN
        EXECUTE IMMEDIATE '
        CREATE TABLE careflow_records (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            age NUMBER,
            language VARCHAR2(20),
            discharge CLOB,
            simplified CLOB,
            risk VARCHAR2(20),
            followup VARCHAR2(30),
            PRIMARY KEY (id)
        )';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    """)

    conn.commit()
    cur.close()
    conn.close()


def save_record(age, language, discharge, simplified, risk, followup):
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("""
    INSERT INTO careflow_records
    (age, language, discharge, simplified, risk, followup)
    VALUES (:1, :2, :3, :4, :5, :6)
    """, (age, language, discharge, simplified, risk, followup))

    conn.commit()
    cur.close()
    conn.close()
